server:
  port: 8083
spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/test
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com.example: debug